In [1]:
import numpy as np
import pandas as pd


In [2]:
data=pd.read_csv("insurance.csv")

In [3]:
data.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
age         1338 non-null int64
sex         1338 non-null object
bmi         1338 non-null float64
children    1338 non-null int64
smoker      1338 non-null object
region      1338 non-null object
charges     1338 non-null float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.2+ KB


In [5]:
data.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [6]:
x=data.iloc[:,0:6]

In [7]:
y=data.iloc[:,6]

In [8]:
x.head()

age     sex     bmi  children smoker     region
0   19  female  27.900         0    yes  southwest
1   18    male  33.770         1     no  southeast
2   28    male  33.000         3     no  southeast
3   33    male  22.705         0     no  northwest
4   32    male  28.880         0     no  northwest

In [9]:
x=data.iloc[:,0:6].values
y=data.iloc[:,6].values

In [10]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [11]:
ct=ColumnTransformer([("oh",OneHotEncoder(),[1,4,5])],remainder="passthrough")

In [12]:
x=ct.fit_transform(x)

In [13]:
x.shape

(1338, 11)

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [16]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [17]:
ann=Sequential()

In [18]:
ann.add(Dense(6,kernel_initializer="random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [19]:
ann.add(Dense(12,kernel_initializer="random_uniform",activation="relu"))

In [20]:
ann.add(Dense(1,kernel_initializer="random_uniform",activation="relu"))

In [38]:
ann.compile("adam","mse",metrics=["mse"])

In [39]:
ann.fit(x_train,y_train,batch_size=32,epochs=1000)

Epoch 1/1000
1070/1070 [==============================] - 0s 237us/sample - loss: 31783183.8206 - mean_squared_error: 31783188.0000
Epoch 2/1000
1070/1070 [==============================] - 0s 47us/sample - loss: 31768577.3533 - mean_squared_error: 31768580.0000
Epoch 3/1000
1070/1070 [==============================] - 0s 48us/sample - loss: 31766077.7084 - mean_squared_error: 31766076.0000
Epoch 4/1000
1070/1070 [==============================] - 0s 53us/sample - loss: 31767482.1458 - mean_squared_error: 31767486.0000
Epoch 5/1000
1070/1070 [==============================] - 0s 48us/sample - loss: 31764680.4336 - mean_squared_error: 31764676.0000
Epoch 6/1000
1070/1070 [==============================] - 0s 47us/sample - loss: 31769851.6150 - mean_squared_error: 31769850.0000
Epoch 7/1000
1070/1070 [==============================] - 0s 43us/sample - loss: 31747493.9626 - mean_squared_error: 31747492.0000
Epoch 8/1000
1070/1070 [==============================] - 0s 60us/sample - loss: 3

1070/1070 [==============================] - 0s 54us/sample - loss: 31494627.2112 - mean_squared_error: 31494624.0000
Epoch 64/1000
1070/1070 [==============================] - 0s 53us/sample - loss: 31499063.7607 - mean_squared_error: 31499062.0000
Epoch 65/1000
1070/1070 [==============================] - ETA: 0s - loss: 52843416.0000 - mean_squared_error: 52843416.00 - 0s 47us/sample - loss: 31484273.7234 - mean_squared_error: 31484276.0000
Epoch 66/1000
1070/1070 [==============================] - 0s 49us/sample - loss: 31480973.0243 - mean_squared_error: 31480970.0000
Epoch 67/1000
1070/1070 [==============================] - 0s 55us/sample - loss: 31471690.7626 - mean_squared_error: 31471690.0000
Epoch 68/1000
1070/1070 [==============================] - 0s 45us/sample - loss: 31473099.7458 - mean_squared_error: 31473100.0000
Epoch 69/1000
1070/1070 [==============================] - 0s 44us/sample - loss: 31461633.0692 - mean_squared_error: 31461634.0000
Epoch 70/1000
1070/1070 

Epoch 124/1000
1070/1070 [==============================] - 0s 55us/sample - loss: 31129745.8991 - mean_squared_error: 31129750.0000
Epoch 125/1000
1070/1070 [==============================] - 0s 49us/sample - loss: 31117024.9383 - mean_squared_error: 31117028.0000
Epoch 126/1000
1070/1070 [==============================] - 0s 69us/sample - loss: 31116531.3720 - mean_squared_error: 31116532.0000
Epoch 127/1000
1070/1070 [==============================] - 0s 64us/sample - loss: 31112818.4748 - mean_squared_error: 31112818.0000
Epoch 128/1000
1070/1070 [==============================] - 0s 55us/sample - loss: 31102428.9907 - mean_squared_error: 31102432.0000
Epoch 129/1000
1070/1070 [==============================] - 0s 51us/sample - loss: 31092261.0991 - mean_squared_error: 31092262.0000
Epoch 130/1000
1070/1070 [==============================] - 0s 63us/sample - loss: 31089476.4112 - mean_squared_error: 31089470.0000
Epoch 131/1000
1070/1070 [==============================] - 0s 50us/s

1070/1070 [==============================] - 0s 30us/sample - loss: 30759983.7925 - mean_squared_error: 30759976.0000
Epoch 186/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 30754339.1551 - mean_squared_error: 30754342.0000
Epoch 187/1000
1070/1070 [==============================] - 0s 29us/sample - loss: 30744594.4075 - mean_squared_error: 30744592.0000
Epoch 188/1000
1070/1070 [==============================] - 0s 28us/sample - loss: 30741430.8561 - mean_squared_error: 30741428.0000
Epoch 189/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 30731622.4710 - mean_squared_error: 30731626.0000
Epoch 190/1000
1070/1070 [==============================] - 0s 29us/sample - loss: 30742669.2299 - mean_squared_error: 30742672.0000
Epoch 191/1000
1070/1070 [==============================] - 0s 28us/sample - loss: 30720649.7570 - mean_squared_error: 30720654.0000
Epoch 192/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 3

1070/1070 [==============================] - 0s 31us/sample - loss: 30351678.5720 - mean_squared_error: 30351676.0000
Epoch 247/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 30341307.5645 - mean_squared_error: 30341312.0000
Epoch 248/1000
1070/1070 [==============================] - 0s 29us/sample - loss: 30338067.1701 - mean_squared_error: 30338070.0000
Epoch 249/1000
1070/1070 [==============================] - 0s 29us/sample - loss: 30325880.8523 - mean_squared_error: 30325884.0000
Epoch 250/1000
1070/1070 [==============================] - 0s 41us/sample - loss: 30325105.4056 - mean_squared_error: 30325110.0000
Epoch 251/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 30316083.0579 - mean_squared_error: 30316084.0000
Epoch 252/1000
1070/1070 [==============================] - 0s 29us/sample - loss: 30310674.9645 - mean_squared_error: 30310676.0000
Epoch 253/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 3

1070/1070 [==============================] - 0s 30us/sample - loss: 29950513.3009 - mean_squared_error: 29950510.0000
Epoch 308/1000
1070/1070 [==============================] - 0s 29us/sample - loss: 29950361.4430 - mean_squared_error: 29950364.0000
Epoch 309/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 29935917.1589 - mean_squared_error: 29935916.0000
Epoch 310/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 29933572.8897 - mean_squared_error: 29933570.0000
Epoch 311/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 29924375.9664 - mean_squared_error: 29924376.0000
Epoch 312/1000
1070/1070 [==============================] - 0s 29us/sample - loss: 29918364.0393 - mean_squared_error: 29918364.0000
Epoch 313/1000
1070/1070 [==============================] - 0s 29us/sample - loss: 29912132.6131 - mean_squared_error: 29912128.0000
Epoch 314/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 2

1070/1070 [==============================] - 0s 34us/sample - loss: 29508828.7477 - mean_squared_error: 29508828.0000
Epoch 369/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 29509354.7664 - mean_squared_error: 29509360.0000
Epoch 370/1000
1070/1070 [==============================] - 0s 39us/sample - loss: 29508476.2262 - mean_squared_error: 29508478.0000
Epoch 371/1000
1070/1070 [==============================] - 0s 44us/sample - loss: 29493543.7308 - mean_squared_error: 29493540.0000
Epoch 372/1000
1070/1070 [==============================] - 0s 36us/sample - loss: 29485489.2075 - mean_squared_error: 29485490.0000
Epoch 373/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 29469270.0075 - mean_squared_error: 29469270.0000
Epoch 374/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 29463165.2187 - mean_squared_error: 29463164.0000
Epoch 375/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 2

1070/1070 [==============================] - 0s 36us/sample - loss: 28914143.7701 - mean_squared_error: 28914144.0000
Epoch 430/1000
1070/1070 [==============================] - 0s 36us/sample - loss: 28916154.1757 - mean_squared_error: 28916154.0000
Epoch 431/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 28889442.4056 - mean_squared_error: 28889446.0000
Epoch 432/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 28881460.0449 - mean_squared_error: 28881458.0000
Epoch 433/1000
1070/1070 [==============================] - 0s 37us/sample - loss: 28874467.3308 - mean_squared_error: 28874468.0000
Epoch 434/1000
1070/1070 [==============================] - 0s 36us/sample - loss: 28865283.9626 - mean_squared_error: 28865284.0000
Epoch 435/1000
1070/1070 [==============================] - 0s 36us/sample - loss: 28850864.9271 - mean_squared_error: 28850866.0000
Epoch 436/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 2

1070/1070 [==============================] - 0s 33us/sample - loss: 28285772.5607 - mean_squared_error: 28285772.0000
Epoch 491/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 28264370.9430 - mean_squared_error: 28264368.0000
Epoch 492/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 28254758.6916 - mean_squared_error: 28254758.0000
Epoch 493/1000
1070/1070 [==============================] - 0s 36us/sample - loss: 28244447.9346 - mean_squared_error: 28244448.0000
Epoch 494/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 28233518.8598 - mean_squared_error: 28233516.0000
Epoch 495/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 28218261.2972 - mean_squared_error: 28218262.0000
Epoch 496/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 28214782.3682 - mean_squared_error: 28214784.0000
Epoch 497/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 2

1070/1070 [==============================] - 0s 36us/sample - loss: 27663434.5645 - mean_squared_error: 27663432.0000
Epoch 552/1000
1070/1070 [==============================] - 0s 40us/sample - loss: 27665550.7065 - mean_squared_error: 27665550.0000
Epoch 553/1000
1070/1070 [==============================] - 0s 36us/sample - loss: 27653999.9308 - mean_squared_error: 27653994.0000
Epoch 554/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 27644688.2056 - mean_squared_error: 27644690.0000
Epoch 555/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 27631821.0019 - mean_squared_error: 27631820.0000
Epoch 556/1000
1070/1070 [==============================] - 0s 35us/sample - loss: 27626880.9047 - mean_squared_error: 27626878.0000
Epoch 557/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 27610909.1514 - mean_squared_error: 27610908.0000
Epoch 558/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 2

1070/1070 [==============================] - 0s 34us/sample - loss: 27164639.6187 - mean_squared_error: 27164646.0000
Epoch 613/1000
1070/1070 [==============================] - 0s 40us/sample - loss: 27155065.4243 - mean_squared_error: 27155066.0000
Epoch 614/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 27147493.0935 - mean_squared_error: 27147496.0000
Epoch 615/1000
1070/1070 [==============================] - 0s 35us/sample - loss: 27143108.2224 - mean_squared_error: 27143112.0000
Epoch 616/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 27133569.4374 - mean_squared_error: 27133570.0000
Epoch 617/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 27127062.6729 - mean_squared_error: 27127066.0000
Epoch 618/1000
1070/1070 [==============================] - 0s 35us/sample - loss: 27124023.6411 - mean_squared_error: 27124022.0000
Epoch 619/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 2

1070/1070 [==============================] - 0s 33us/sample - loss: 26733726.0262 - mean_squared_error: 26733724.0000
Epoch 674/1000
1070/1070 [==============================] - 0s 29us/sample - loss: 26719428.4150 - mean_squared_error: 26719432.0000
Epoch 675/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 26712955.6897 - mean_squared_error: 26712954.0000
Epoch 676/1000
1070/1070 [==============================] - 0s 36us/sample - loss: 26701598.9757 - mean_squared_error: 26701600.0000
Epoch 677/1000
1070/1070 [==============================] - 0s 35us/sample - loss: 26695998.6841 - mean_squared_error: 26696002.0000
Epoch 678/1000
1070/1070 [==============================] - 0s 36us/sample - loss: 26693582.6075 - mean_squared_error: 26693586.0000
Epoch 679/1000
1070/1070 [==============================] - 0s 35us/sample - loss: 26683265.6467 - mean_squared_error: 26683270.0000
Epoch 680/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 2

1070/1070 [==============================] - 0s 36us/sample - loss: 26338701.1916 - mean_squared_error: 26338700.0000
Epoch 735/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 26335332.6542 - mean_squared_error: 26335332.0000
Epoch 736/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 26327029.8449 - mean_squared_error: 26327028.0000
Epoch 737/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 26334603.4542 - mean_squared_error: 26334604.0000
Epoch 738/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 26319377.6336 - mean_squared_error: 26319380.0000
Epoch 739/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 26309547.9402 - mean_squared_error: 26309548.0000
Epoch 740/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 26304075.5738 - mean_squared_error: 26304076.0000
Epoch 741/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 2

1070/1070 [==============================] - 0s 31us/sample - loss: 25989249.9888 - mean_squared_error: 25989250.0000
Epoch 796/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 25985437.8467 - mean_squared_error: 25985438.0000
Epoch 797/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 25980863.9327 - mean_squared_error: 25980864.0000
Epoch 798/1000
1070/1070 [==============================] - 0s 36us/sample - loss: 25976644.4411 - mean_squared_error: 25976642.0000
Epoch 799/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 25967120.2168 - mean_squared_error: 25967118.0000
Epoch 800/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 25964838.9458 - mean_squared_error: 25964834.0000
Epoch 801/1000
1070/1070 [==============================] - 0s 35us/sample - loss: 25961883.9355 - mean_squared_error: 25961888.0000
Epoch 802/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 2

1070/1070 [==============================] - 0s 34us/sample - loss: 25674941.3682 - mean_squared_error: 25674942.0000
Epoch 857/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 25684706.9196 - mean_squared_error: 25684706.0000
Epoch 858/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 25673370.2280 - mean_squared_error: 25673372.0000
Epoch 859/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 25664895.0355 - mean_squared_error: 25664892.0000
Epoch 860/1000
1070/1070 [==============================] - 0s 36us/sample - loss: 25664586.6589 - mean_squared_error: 25664588.0000
Epoch 861/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 25658082.1981 - mean_squared_error: 25658078.0000
Epoch 862/1000
1070/1070 [==============================] - 0s 36us/sample - loss: 25650081.2935 - mean_squared_error: 25650082.0000
Epoch 863/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 2

1070/1070 [==============================] - 0s 34us/sample - loss: 25401346.4822 - mean_squared_error: 25401350.0000
Epoch 918/1000
1070/1070 [==============================] - 0s 44us/sample - loss: 25398086.6589 - mean_squared_error: 25398086.0000
Epoch 919/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 25394760.5383 - mean_squared_error: 25394764.0000
Epoch 920/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 25389491.0766 - mean_squared_error: 25389490.0000
Epoch 921/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 25387919.4579 - mean_squared_error: 25387920.0000
Epoch 922/1000
1070/1070 [==============================] - 0s 35us/sample - loss: 25385137.4654 - mean_squared_error: 25385136.0000
Epoch 923/1000
1070/1070 [==============================] - 0s 38us/sample - loss: 25376420.8075 - mean_squared_error: 25376422.0000
Epoch 924/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 2

1070/1070 [==============================] - 0s 34us/sample - loss: 25155964.4486 - mean_squared_error: 25155964.0000
Epoch 979/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 25147541.4355 - mean_squared_error: 25147542.0000
Epoch 980/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 25141592.2467 - mean_squared_error: 25141596.0000
Epoch 981/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 25140413.8262 - mean_squared_error: 25140418.0000
Epoch 982/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 25135907.6729 - mean_squared_error: 25135914.0000
Epoch 983/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 25134692.2243 - mean_squared_error: 25134690.0000
Epoch 984/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 25129520.6131 - mean_squared_error: 25129522.0000
Epoch 985/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 2

In [40]:
ypred=ann.predict(x_test)

In [41]:
ypred

array([[ 9788.951 ],
       [10328.748 ],
       [48330.707 ],
       [14539.905 ],
       [10491.204 ],
       [ 5704.5493],
       [ 3273.4531],
       [14346.496 ],
       [ 9393.459 ],
       [ 6544.0464],
       [ 8409.518 ],
       [11483.174 ],
       [ 8973.508 ],
       [ 5170.354 ],
       [24963.576 ],
       [12506.98  ],
       [12907.918 ],
       [ 4270.0273],
       [ 7876.7437],
       [27400.291 ],
       [27527.17  ],
       [14309.436 ],
       [12451.316 ],
       [30278.58  ],
       [ 3282.7012],
       [ 6029.6694],
       [ 6009.0938],
       [10315.316 ],
       [ 4784.46  ],
       [10181.711 ],
       [ 9769.138 ],
       [51504.934 ],
       [12896.227 ],
       [10696.611 ],
       [16579.62  ],
       [ 6086.799 ],
       [ 9913.389 ],
       [37525.363 ],
       [35784.836 ],
       [ 3833.416 ],
       [ 7232.676 ],
       [ 4049.938 ],
       [26768.66  ],
       [46516.598 ],
       [34218.35  ],
       [ 4599.576 ],
       [12469.524 ],
       [ 8164

In [42]:
y_test

array([ 9724.53    ,  8547.6913  , 45702.02235 , 12950.0712  ,
        9644.2525  ,  4500.33925 ,  2198.18985 , 11436.73815 ,
        7537.1639  ,  5425.02335 ,  6753.038   , 10493.9458  ,
        7337.748   ,  4185.0979  , 18310.742   , 10702.6424  ,
       12523.6048  ,  3490.5491  ,  6457.8434  , 33475.81715 ,
       23967.38305 , 12643.3778  , 23045.56616 , 23065.4207  ,
        1674.6323  ,  4667.60765 ,  3732.6251  ,  7682.67    ,
        3756.6216  ,  8413.46305 ,  8059.6791  , 48970.2476  ,
       12979.358   , 20630.28351 , 14571.8908  ,  4137.5227  ,
        8347.1643  , 51194.55914 , 40003.33225 ,  1880.487   ,
        5458.04645 ,  2867.1196  , 20149.3229  , 47496.49445 ,
       36149.4835  , 26018.95052 , 19749.38338 ,  6940.90985 ,
        4718.20355 , 22192.43711 ,  2899.48935 , 18838.70366 ,
       23568.272   , 46255.1125  , 24227.33724 ,  3268.84665 ,
        2322.6218  ,  8827.2099  , 14478.33015 , 13112.6048  ,
        1253.936   , 46718.16325 , 13919.8229  ,  9630.

In [43]:
yy=ann.predict(sc.transform(ct.transform([[19,"female",27.900,0,"yes","southwest"]])))

In [44]:
yy

array([[23764.443]], dtype=float32)

In [45]:
ann.predict(sc.transform(ct.transform([[18,"male",33.770,0,"no","southwest"]])))

array([[2190.8728]], dtype=float32)

In [46]:
ann.predict(sc.transform(ct.transform([[28,"male",33.00,3,"no","southwest"]])))

array([[4716.641]], dtype=float32)