In [1]:
import numpy as np
import pandas as pd


In [2]:
data=pd.read_csv("Categorical.csv")

In [3]:
data.head()

name  Longitude   Latitude      continent
0        Aruba -69.982677  12.520880  North America
1  Afghanistan  66.004734  33.835231           Asia
2       Angola  17.537368 -12.293361         Africa
3     Anguilla -63.064989  18.223959  North America
4      Albania  20.049834  41.142450         Europe

In [4]:
data.isnull().sum()

name         0
Longitude    0
Latitude     0
continent    0
dtype: int64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 4 columns):
name         241 non-null object
Longitude    241 non-null float64
Latitude     241 non-null float64
continent    241 non-null object
dtypes: float64(2), object(2)
memory usage: 7.6+ KB


In [6]:
data["name"].unique()

array(['Aruba', 'Afghanistan', 'Angola', 'Anguilla', 'Albania', 'Aland',
       'Andorra', 'United Arab Emirates', 'Argentina', 'Armenia',
       'American Samoa', 'Antarctica', 'Ashmore and Cartier Is.',
       'Fr. S. Antarctic Lands', 'Antigua and Barb.', 'Australia',
       'Austria', 'Azerbaijan', 'Burundi', 'Belgium', 'Benin',
       'Burkina Faso', 'Bangladesh', 'Bulgaria', 'Bahrain', 'Canada',
       'Bahamas', 'Bosnia and Herz.', 'St-Barthélemy', 'Belarus',
       'Belize', 'Bermuda', 'Bolivia', 'Brazil', 'Barbados', 'Brunei',
       'Bhutan', 'Botswana', 'Central African Rep.', 'Switzerland',
       'Chile', 'China', "Côte d'Ivoire", 'Cameroon', 'Dem. Rep. Congo',
       'Congo', 'Cook Is.', 'Colombia', 'Comoros', 'Cape Verde',
       'Costa Rica', 'Cuba', 'Curaçao', 'Cayman Is.', 'N. Cyprus',
       'Cyprus', 'Czech Rep.', 'Germany', 'Djibouti', 'Dominica',
       'Denmark', 'Dominican Rep.', 'Algeria', 'Ecuador', 'Egypt',
       'Eritrea', 'Spain', 'Estonia', 'Ethiopia',

In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data["name"]=le.fit_transform(data["name"])

In [9]:
x=data.iloc[:,0:3]
y=data.iloc[:,3]

In [10]:
x.head()

name  Longitude   Latitude
0    12 -69.982677  12.520880
1     0  66.004734  33.835231
2     6  17.537368 -12.293361
3     7 -63.064989  18.223959
4     2  20.049834  41.142450

In [11]:
y.head()

0    North America
1             Asia
2           Africa
3    North America
4           Europe
Name: continent, dtype: object

In [16]:
x=data.iloc[:,0:3].values
y=data.iloc[:,3:4].values

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [19]:
one=OneHotEncoder()
z=one.fit_transform(y[:,0:1]).toarray()
y=np.delete(y,0,axis=1)
y=np.concatenate((z,y),axis=1)

In [20]:
y

array([[0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [0.0, 0.0, 1.0, ..., 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       [1.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object)

In [21]:
y.shape

(241, 8)

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [23]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [26]:
cat=Sequential()

In [29]:
cat.add(Dense(3,kernel_initializer="random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [30]:
cat.add(Dense(6,kernel_initializer="random_uniform",activation="relu"))

In [31]:
cat.add(Dense(8,kernel_initializer="random_uniform",activation="softmax"))

In [32]:
cat.compile("adam","categorical_crossentropy",metrics=["accuracy"])

In [34]:
cat.fit(x_train,y_train,batch_size=32,epochs=1500)

Epoch 1/1500
192/192 [==============================] - 0s 271us/sample - loss: 0.9727 - acc: 0.6823
Epoch 2/1500
192/192 [==============================] - 0s 188us/sample - loss: 0.9714 - acc: 0.6823
Epoch 3/1500
192/192 [==============================] - 0s 190us/sample - loss: 0.9708 - acc: 0.6823
Epoch 4/1500
192/192 [==============================] - 0s 167us/sample - loss: 0.9698 - acc: 0.6823
Epoch 5/1500
192/192 [==============================] - 0s 156us/sample - loss: 0.9691 - acc: 0.6823
Epoch 6/1500
192/192 [==============================] - 0s 182us/sample - loss: 0.9685 - acc: 0.6823
Epoch 7/1500
192/192 [==============================] - 0s 234us/sample - loss: 0.9675 - acc: 0.6823
Epoch 8/1500
192/192 [==============================] - 0s 177us/sample - loss: 0.9667 - acc: 0.6823
Epoch 9/1500
192/192 [==============================] - 0s 177us/sample - loss: 0.9659 - acc: 0.6823
Epoch 10/1500
192/192 [==============================] - 0s 172us/sample - loss: 0.9652 - a

192/192 [==============================] - 0s 271us/sample - loss: 0.9107 - acc: 0.7031
Epoch 82/1500
192/192 [==============================] - 0s 161us/sample - loss: 0.9100 - acc: 0.7031
Epoch 83/1500
192/192 [==============================] - 0s 146us/sample - loss: 0.9091 - acc: 0.7031
Epoch 84/1500
192/192 [==============================] - 0s 135us/sample - loss: 0.9084 - acc: 0.7031
Epoch 85/1500
192/192 [==============================] - 0s 156us/sample - loss: 0.9076 - acc: 0.7031
Epoch 86/1500
192/192 [==============================] - 0s 182us/sample - loss: 0.9070 - acc: 0.7135
Epoch 87/1500
192/192 [==============================] - 0s 151us/sample - loss: 0.9061 - acc: 0.7135
Epoch 88/1500
192/192 [==============================] - 0s 151us/sample - loss: 0.9055 - acc: 0.7135
Epoch 89/1500
192/192 [==============================] - 0s 167us/sample - loss: 0.9048 - acc: 0.7135
Epoch 90/1500
192/192 [==============================] - 0s 156us/sample - loss: 0.9039 - acc: 0

192/192 [==============================] - 0s 178us/sample - loss: 0.8570 - acc: 0.7292
Epoch 161/1500
192/192 [==============================] - 0s 217us/sample - loss: 0.8566 - acc: 0.7292
Epoch 162/1500
192/192 [==============================] - 0s 193us/sample - loss: 0.8563 - acc: 0.7292
Epoch 163/1500
192/192 [==============================] - 0s 130us/sample - loss: 0.8556 - acc: 0.7292
Epoch 164/1500
192/192 [==============================] - 0s 146us/sample - loss: 0.8551 - acc: 0.7292
Epoch 165/1500
192/192 [==============================] - 0s 161us/sample - loss: 0.8544 - acc: 0.7292
Epoch 166/1500
192/192 [==============================] - 0s 130us/sample - loss: 0.8540 - acc: 0.7292
Epoch 167/1500
192/192 [==============================] - 0s 151us/sample - loss: 0.8535 - acc: 0.7292
Epoch 168/1500
192/192 [==============================] - 0s 156us/sample - loss: 0.8529 - acc: 0.7292
Epoch 169/1500
192/192 [==============================] - 0s 172us/sample - loss: 0.8526

192/192 [==============================] - 0s 198us/sample - loss: 0.8233 - acc: 0.7344
Epoch 240/1500
192/192 [==============================] - 0s 167us/sample - loss: 0.8225 - acc: 0.7344
Epoch 241/1500
192/192 [==============================] - 0s 161us/sample - loss: 0.8224 - acc: 0.7344
Epoch 242/1500
192/192 [==============================] - 0s 146us/sample - loss: 0.8219 - acc: 0.7344
Epoch 243/1500
192/192 [==============================] - 0s 115us/sample - loss: 0.8215 - acc: 0.7344
Epoch 244/1500
192/192 [==============================] - 0s 135us/sample - loss: 0.8212 - acc: 0.7344
Epoch 245/1500
192/192 [==============================] - 0s 203us/sample - loss: 0.8211 - acc: 0.7344
Epoch 246/1500
192/192 [==============================] - 0s 161us/sample - loss: 0.8204 - acc: 0.7344
Epoch 247/1500
192/192 [==============================] - 0s 130us/sample - loss: 0.8200 - acc: 0.7344
Epoch 248/1500
192/192 [==============================] - 0s 151us/sample - loss: 0.8197

192/192 [==============================] - 0s 198us/sample - loss: 0.7969 - acc: 0.7344
Epoch 319/1500
192/192 [==============================] - 0s 203us/sample - loss: 0.7965 - acc: 0.7344
Epoch 320/1500
192/192 [==============================] - 0s 135us/sample - loss: 0.7963 - acc: 0.7344
Epoch 321/1500
192/192 [==============================] - 0s 151us/sample - loss: 0.7960 - acc: 0.7344
Epoch 322/1500
192/192 [==============================] - 0s 135us/sample - loss: 0.7956 - acc: 0.7344
Epoch 323/1500
192/192 [==============================] - 0s 115us/sample - loss: 0.7952 - acc: 0.7344
Epoch 324/1500
192/192 [==============================] - 0s 167us/sample - loss: 0.7951 - acc: 0.7344
Epoch 325/1500
192/192 [==============================] - 0s 141us/sample - loss: 0.7949 - acc: 0.7344
Epoch 326/1500
192/192 [==============================] - 0s 146us/sample - loss: 0.7942 - acc: 0.7344
Epoch 327/1500
192/192 [==============================] - 0s 109us/sample - loss: 0.7940

192/192 [==============================] - 0s 208us/sample - loss: 0.7730 - acc: 0.7344
Epoch 398/1500
192/192 [==============================] - 0s 172us/sample - loss: 0.7727 - acc: 0.7292
Epoch 399/1500
192/192 [==============================] - 0s 156us/sample - loss: 0.7724 - acc: 0.7344
Epoch 400/1500
192/192 [==============================] - 0s 141us/sample - loss: 0.7721 - acc: 0.7344
Epoch 401/1500
192/192 [==============================] - 0s 146us/sample - loss: 0.7719 - acc: 0.7344
Epoch 402/1500
192/192 [==============================] - 0s 146us/sample - loss: 0.7713 - acc: 0.7344
Epoch 403/1500
192/192 [==============================] - 0s 167us/sample - loss: 0.7712 - acc: 0.7344
Epoch 404/1500
192/192 [==============================] - 0s 146us/sample - loss: 0.7709 - acc: 0.7344
Epoch 405/1500
192/192 [==============================] - 0s 156us/sample - loss: 0.7706 - acc: 0.7344
Epoch 406/1500
192/192 [==============================] - 0s 151us/sample - loss: 0.7704

Epoch 476/1500
192/192 [==============================] - 0s 193us/sample - loss: 0.7427 - acc: 0.7448
Epoch 477/1500
192/192 [==============================] - 0s 151us/sample - loss: 0.7425 - acc: 0.7448
Epoch 478/1500
192/192 [==============================] - 0s 167us/sample - loss: 0.7420 - acc: 0.7396
Epoch 479/1500
192/192 [==============================] - 0s 125us/sample - loss: 0.7415 - acc: 0.7448
Epoch 480/1500
192/192 [==============================] - 0s 156us/sample - loss: 0.7412 - acc: 0.7448
Epoch 481/1500
192/192 [==============================] - 0s 151us/sample - loss: 0.7410 - acc: 0.7396
Epoch 482/1500
192/192 [==============================] - 0s 203us/sample - loss: 0.7406 - acc: 0.7396
Epoch 483/1500
192/192 [==============================] - 0s 135us/sample - loss: 0.7402 - acc: 0.7396
Epoch 484/1500
192/192 [==============================] - 0s 156us/sample - loss: 0.7397 - acc: 0.7396
Epoch 485/1500
192/192 [==============================] - 0s 151us/sample

192/192 [==============================] - 0s 182us/sample - loss: 0.7148 - acc: 0.7500
Epoch 556/1500
192/192 [==============================] - 0s 177us/sample - loss: 0.7145 - acc: 0.7500
Epoch 557/1500
192/192 [==============================] - 0s 130us/sample - loss: 0.7144 - acc: 0.7500
Epoch 558/1500
192/192 [==============================] - 0s 136us/sample - loss: 0.7138 - acc: 0.7500
Epoch 559/1500
192/192 [==============================] - 0s 179us/sample - loss: 0.7136 - acc: 0.7500
Epoch 560/1500
192/192 [==============================] - 0s 136us/sample - loss: 0.7132 - acc: 0.7500
Epoch 561/1500
192/192 [==============================] - 0s 229us/sample - loss: 0.7129 - acc: 0.7500
Epoch 562/1500
192/192 [==============================] - 0s 162us/sample - loss: 0.7125 - acc: 0.7500
Epoch 563/1500
192/192 [==============================] - 0s 148us/sample - loss: 0.7122 - acc: 0.7500
Epoch 564/1500
192/192 [==============================] - 0s 156us/sample - loss: 0.7121

192/192 [==============================] - 0s 146us/sample - loss: 0.6896 - acc: 0.7552
Epoch 635/1500
192/192 [==============================] - 0s 177us/sample - loss: 0.6893 - acc: 0.7552
Epoch 636/1500
192/192 [==============================] - 0s 130us/sample - loss: 0.6891 - acc: 0.7552
Epoch 637/1500
192/192 [==============================] - 0s 151us/sample - loss: 0.6887 - acc: 0.7552
Epoch 638/1500
192/192 [==============================] - 0s 180us/sample - loss: 0.6888 - acc: 0.7552
Epoch 639/1500
192/192 [==============================] - 0s 115us/sample - loss: 0.6882 - acc: 0.7552
Epoch 640/1500
192/192 [==============================] - 0s 167us/sample - loss: 0.6880 - acc: 0.7552
Epoch 641/1500
192/192 [==============================] - 0s 141us/sample - loss: 0.6879 - acc: 0.7552
Epoch 642/1500
192/192 [==============================] - 0s 146us/sample - loss: 0.6875 - acc: 0.7552
Epoch 643/1500
192/192 [==============================] - 0s 156us/sample - loss: 0.6872

192/192 [==============================] - 0s 187us/sample - loss: 0.6711 - acc: 0.7604
Epoch 714/1500
192/192 [==============================] - 0s 172us/sample - loss: 0.6707 - acc: 0.7604
Epoch 715/1500
192/192 [==============================] - 0s 167us/sample - loss: 0.6707 - acc: 0.7604
Epoch 716/1500
192/192 [==============================] - 0s 151us/sample - loss: 0.6704 - acc: 0.7604
Epoch 717/1500
192/192 [==============================] - 0s 156us/sample - loss: 0.6703 - acc: 0.7604
Epoch 718/1500
192/192 [==============================] - 0s 188us/sample - loss: 0.6699 - acc: 0.7604
Epoch 719/1500
192/192 [==============================] - 0s 151us/sample - loss: 0.6697 - acc: 0.7604
Epoch 720/1500
192/192 [==============================] - 0s 167us/sample - loss: 0.6695 - acc: 0.7656
Epoch 721/1500
192/192 [==============================] - 0s 151us/sample - loss: 0.6694 - acc: 0.7656
Epoch 722/1500
192/192 [==============================] - 0s 136us/sample - loss: 0.6692

192/192 [==============================] - 0s 115us/sample - loss: 0.6577 - acc: 0.7708
Epoch 793/1500
192/192 [==============================] - 0s 120us/sample - loss: 0.6576 - acc: 0.7708
Epoch 794/1500
192/192 [==============================] - 0s 99us/sample - loss: 0.6574 - acc: 0.7708
Epoch 795/1500
192/192 [==============================] - 0s 104us/sample - loss: 0.6574 - acc: 0.7708
Epoch 796/1500
192/192 [==============================] - 0s 104us/sample - loss: 0.6571 - acc: 0.7708
Epoch 797/1500
192/192 [==============================] - 0s 104us/sample - loss: 0.6571 - acc: 0.7708
Epoch 798/1500
192/192 [==============================] - 0s 104us/sample - loss: 0.6571 - acc: 0.7708
Epoch 799/1500
192/192 [==============================] - 0s 135us/sample - loss: 0.6570 - acc: 0.7708
Epoch 800/1500
192/192 [==============================] - 0s 104us/sample - loss: 0.6567 - acc: 0.7656
Epoch 801/1500
192/192 [==============================] - 0s 104us/sample - loss: 0.6566 

192/192 [==============================] - 0s 115us/sample - loss: 0.6492 - acc: 0.7656
Epoch 872/1500
192/192 [==============================] - 0s 115us/sample - loss: 0.6491 - acc: 0.7656
Epoch 873/1500
192/192 [==============================] - 0s 120us/sample - loss: 0.6491 - acc: 0.7656
Epoch 874/1500
192/192 [==============================] - 0s 151us/sample - loss: 0.6489 - acc: 0.7656
Epoch 875/1500
192/192 [==============================] - 0s 109us/sample - loss: 0.6488 - acc: 0.7656
Epoch 876/1500
192/192 [==============================] - 0s 104us/sample - loss: 0.6487 - acc: 0.7656
Epoch 877/1500
192/192 [==============================] - 0s 99us/sample - loss: 0.6489 - acc: 0.7656
Epoch 878/1500
192/192 [==============================] - 0s 133us/sample - loss: 0.6487 - acc: 0.7656
Epoch 879/1500
192/192 [==============================] - 0s 125us/sample - loss: 0.6485 - acc: 0.7656
Epoch 880/1500
192/192 [==============================] - 0s 104us/sample - loss: 0.6484 

192/192 [==============================] - 0s 161us/sample - loss: 0.6430 - acc: 0.7656
Epoch 951/1500
192/192 [==============================] - 0s 115us/sample - loss: 0.6431 - acc: 0.7656
Epoch 952/1500
192/192 [==============================] - 0s 130us/sample - loss: 0.6429 - acc: 0.7656
Epoch 953/1500
192/192 [==============================] - 0s 104us/sample - loss: 0.6436 - acc: 0.7656
Epoch 954/1500
192/192 [==============================] - 0s 99us/sample - loss: 0.6430 - acc: 0.7656
Epoch 955/1500
192/192 [==============================] - 0s 94us/sample - loss: 0.6429 - acc: 0.7656
Epoch 956/1500
192/192 [==============================] - 0s 109us/sample - loss: 0.6426 - acc: 0.7656
Epoch 957/1500
192/192 [==============================] - 0s 120us/sample - loss: 0.6429 - acc: 0.7656
Epoch 958/1500
192/192 [==============================] - 0s 177us/sample - loss: 0.6425 - acc: 0.7708
Epoch 959/1500
192/192 [==============================] - 0s 109us/sample - loss: 0.6427 -

192/192 [==============================] - 0s 278us/sample - loss: 0.6337 - acc: 0.7552
Epoch 1030/1500
192/192 [==============================] - 0s 177us/sample - loss: 0.6334 - acc: 0.7604
Epoch 1031/1500
192/192 [==============================] - 0s 188us/sample - loss: 0.6332 - acc: 0.7552
Epoch 1032/1500
192/192 [==============================] - 0s 141us/sample - loss: 0.6332 - acc: 0.7552
Epoch 1033/1500
192/192 [==============================] - 0s 134us/sample - loss: 0.6329 - acc: 0.7552
Epoch 1034/1500
192/192 [==============================] - 0s 159us/sample - loss: 0.6326 - acc: 0.7552
Epoch 1035/1500
192/192 [==============================] - 0s 177us/sample - loss: 0.6327 - acc: 0.7552
Epoch 1036/1500
192/192 [==============================] - 0s 141us/sample - loss: 0.6323 - acc: 0.7552
Epoch 1037/1500
192/192 [==============================] - 0s 166us/sample - loss: 0.6321 - acc: 0.7552
Epoch 1038/1500
192/192 [==============================] - 0s 161us/sample - los

Epoch 1108/1500
192/192 [==============================] - 0s 161us/sample - loss: 0.6227 - acc: 0.7552
Epoch 1109/1500
192/192 [==============================] - 0s 135us/sample - loss: 0.6227 - acc: 0.7552
Epoch 1110/1500
192/192 [==============================] - 0s 216us/sample - loss: 0.6225 - acc: 0.7552
Epoch 1111/1500
192/192 [==============================] - 0s 167us/sample - loss: 0.6224 - acc: 0.7552
Epoch 1112/1500
192/192 [==============================] - 0s 177us/sample - loss: 0.6225 - acc: 0.7552
Epoch 1113/1500
192/192 [==============================] - 0s 208us/sample - loss: 0.6225 - acc: 0.7552
Epoch 1114/1500
192/192 [==============================] - 0s 172us/sample - loss: 0.6222 - acc: 0.7552
Epoch 1115/1500
192/192 [==============================] - 0s 135us/sample - loss: 0.6222 - acc: 0.7552
Epoch 1116/1500
192/192 [==============================] - 0s 198us/sample - loss: 0.6221 - acc: 0.7552
Epoch 1117/1500
192/192 [==============================] - 0s 13

192/192 [==============================] - 0s 222us/sample - loss: 0.6167 - acc: 0.7552
Epoch 1187/1500
192/192 [==============================] - 0s 172us/sample - loss: 0.6171 - acc: 0.7552
Epoch 1188/1500
192/192 [==============================] - 0s 135us/sample - loss: 0.6167 - acc: 0.7552
Epoch 1189/1500
192/192 [==============================] - 0s 156us/sample - loss: 0.6165 - acc: 0.7552
Epoch 1190/1500
192/192 [==============================] - 0s 198us/sample - loss: 0.6165 - acc: 0.7552
Epoch 1191/1500
192/192 [==============================] - 0s 161us/sample - loss: 0.6164 - acc: 0.7552
Epoch 1192/1500
192/192 [==============================] - 0s 156us/sample - loss: 0.6162 - acc: 0.7552
Epoch 1193/1500
192/192 [==============================] - 0s 156us/sample - loss: 0.6162 - acc: 0.7552
Epoch 1194/1500
192/192 [==============================] - 0s 146us/sample - loss: 0.6161 - acc: 0.7552
Epoch 1195/1500
192/192 [==============================] - 0s 188us/sample - los

Epoch 1265/1500
192/192 [==============================] - 0s 240us/sample - loss: 0.6098 - acc: 0.7552
Epoch 1266/1500
192/192 [==============================] - 0s 125us/sample - loss: 0.6097 - acc: 0.7552
Epoch 1267/1500
192/192 [==============================] - 0s 135us/sample - loss: 0.6096 - acc: 0.7552
Epoch 1268/1500
192/192 [==============================] - 0s 156us/sample - loss: 0.6095 - acc: 0.7552
Epoch 1269/1500
192/192 [==============================] - 0s 172us/sample - loss: 0.6096 - acc: 0.7552
Epoch 1270/1500
192/192 [==============================] - 0s 141us/sample - loss: 0.6096 - acc: 0.7552
Epoch 1271/1500
192/192 [==============================] - 0s 104us/sample - loss: 0.6096 - acc: 0.7552
Epoch 1272/1500
192/192 [==============================] - 0s 182us/sample - loss: 0.6092 - acc: 0.7552
Epoch 1273/1500
192/192 [==============================] - 0s 182us/sample - loss: 0.6093 - acc: 0.7552
Epoch 1274/1500
192/192 [==============================] - 0s 14

192/192 [==============================] - 0s 156us/sample - loss: 0.6055 - acc: 0.7500
Epoch 1344/1500
192/192 [==============================] - 0s 193us/sample - loss: 0.6054 - acc: 0.7500
Epoch 1345/1500
192/192 [==============================] - 0s 177us/sample - loss: 0.6052 - acc: 0.7500
Epoch 1346/1500
192/192 [==============================] - 0s 156us/sample - loss: 0.6053 - acc: 0.7500
Epoch 1347/1500
192/192 [==============================] - 0s 157us/sample - loss: 0.6052 - acc: 0.7500
Epoch 1348/1500
192/192 [==============================] - 0s 161us/sample - loss: 0.6050 - acc: 0.7500
Epoch 1349/1500
192/192 [==============================] - 0s 151us/sample - loss: 0.6048 - acc: 0.7500
Epoch 1350/1500
192/192 [==============================] - 0s 150us/sample - loss: 0.6049 - acc: 0.7500
Epoch 1351/1500
192/192 [==============================] - 0s 177us/sample - loss: 0.6051 - acc: 0.7500
Epoch 1352/1500
192/192 [==============================] - 0s 141us/sample - los

Epoch 1422/1500
192/192 [==============================] - 0s 198us/sample - loss: 0.6018 - acc: 0.7552
Epoch 1423/1500
192/192 [==============================] - 0s 188us/sample - loss: 0.6022 - acc: 0.7552
Epoch 1424/1500
192/192 [==============================] - 0s 156us/sample - loss: 0.6017 - acc: 0.7552
Epoch 1425/1500
192/192 [==============================] - 0s 156us/sample - loss: 0.6017 - acc: 0.7552
Epoch 1426/1500
192/192 [==============================] - 0s 151us/sample - loss: 0.6020 - acc: 0.7552
Epoch 1427/1500
192/192 [==============================] - 0s 141us/sample - loss: 0.6017 - acc: 0.7552
Epoch 1428/1500
192/192 [==============================] - 0s 173us/sample - loss: 0.6018 - acc: 0.7552
Epoch 1429/1500
192/192 [==============================] - 0s 173us/sample - loss: 0.6016 - acc: 0.7552
Epoch 1430/1500
192/192 [==============================] - 0s 146us/sample - loss: 0.6015 - acc: 0.7552
Epoch 1431/1500
192/192 [==============================] - 0s 15

192/192 [==============================] - 0s 141us/sample - loss: 0.5992 - acc: 0.7552


In [35]:
ypred=cat.predict(x_test)

In [36]:
ypred

array([[1.75285414e-01, 5.19557266e-23, 7.95588672e-01, 2.91237440e-02,
        1.99353940e-06, 1.34006117e-09, 1.28601922e-30, 2.02445506e-07],
       [3.82473767e-01, 1.91376954e-02, 8.75807181e-02, 2.67765514e-04,
        2.29865266e-03, 2.37184420e-01, 1.73458382e-01, 9.75986868e-02],
       [3.82473767e-01, 1.91376954e-02, 8.75807181e-02, 2.67765514e-04,
        2.29865266e-03, 2.37184420e-01, 1.73458382e-01, 9.75986868e-02],
       [3.82473767e-01, 1.91376954e-02, 8.75807181e-02, 2.67765514e-04,
        2.29865266e-03, 2.37184420e-01, 1.73458382e-01, 9.75986868e-02],
       [3.88331591e-06, 0.00000000e+00, 1.84316944e-13, 8.72389495e-01,
        1.27606452e-01, 8.71872279e-12, 0.00000000e+00, 7.70864190e-08],
       [6.64170040e-03, 5.48642813e-33, 4.75872639e-06, 9.90989387e-01,
        2.36345339e-03, 6.43573195e-10, 0.00000000e+00, 7.19956802e-07],
       [3.99646699e-01, 1.31687975e-14, 5.92934787e-01, 7.30671035e-03,
        5.02679468e-05, 3.98172642e-06, 8.43903154e-19, 5.

In [37]:
y_test

array([[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
       [0.0, 0.0, 0.

In [40]:
data.head()

name  Longitude   Latitude      continent
0    12 -69.982677  12.520880  North America
1     0  66.004734  33.835231           Asia
2     6  17.537368 -12.293361         Africa
3     7 -63.064989  18.223959  North America
4     2  20.049834  41.142450         Europe

In [41]:

cat.predict_classes(sc.transform([[12,-69.982677,12.52088]]))

array([4], dtype=int64)

In [42]:

cat.predict(sc.transform([[12,-69.982677,12.52088]]))

array([[8.2803651e-04, 8.5638417e-19, 4.5460773e-09, 6.8057659e-03,
        9.7996867e-01, 9.5693493e-04, 7.6440898e-25, 1.1440649e-02]],
      dtype=float32)

In [43]:

cat.predict_classes(sc.transform([[0,66.004734,33.835231]]))

array([2], dtype=int64)

In [44]:

cat.predict(sc.transform([[0,66.004734,33.835231]]))

array([[6.7412831e-02, 1.2188864e-22, 9.2735392e-01, 5.2330378e-03,
        1.9946707e-07, 2.9876676e-10, 8.5000512e-30, 3.8128796e-08]],
      dtype=float32)