In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("Bank_Personal_Loan_Modelling.csv")

In [3]:
data.head()

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0   
1   2   45          19      34     90089       3    1.5          1         0   
2   3   39          15      11     94720       1    1.0          1         0   
3   4   35           9     100     94112       1    2.7          2         0   
4   5   35           8      45     91330       4    1.0          2         0   

   Personal Loan  Securities Account  CD Account  Online  CreditCard  
0              0                   1           0       0           0  
1              0                   1           0       0           0  
2              0                   0           0       0           0  
3              0                   0           0       0           0  
4              0                   0           0       0           1

In [4]:
data.isnull().sum()

ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
ID                    5000 non-null int64
Age                   5000 non-null int64
Experience            5000 non-null int64
Income                5000 non-null int64
ZIP Code              5000 non-null int64
Family                5000 non-null int64
CCAvg                 5000 non-null float64
Education             5000 non-null int64
Mortgage              5000 non-null int64
Personal Loan         5000 non-null int64
Securities Account    5000 non-null int64
CD Account            5000 non-null int64
Online                5000 non-null int64
CreditCard            5000 non-null int64
dtypes: float64(1), int64(13)
memory usage: 547.0 KB


In [6]:
data.drop(columns=["ID","ZIP Code"],inplace=True)

In [7]:
data.head()

Age  Experience  Income  Family  CCAvg  Education  Mortgage  Personal Loan  \
0   25           1      49       4    1.6          1         0              0   
1   45          19      34       3    1.5          1         0              0   
2   39          15      11       1    1.0          1         0              0   
3   35           9     100       1    2.7          2         0              0   
4   35           8      45       4    1.0          2         0              0   

   Securities Account  CD Account  Online  CreditCard  
0                   1           0       0           0  
1                   1           0       0           0  
2                   0           0       0           0  
3                   0           0       0           0  
4                   0           0       0           1

In [8]:
x=data.iloc[:,[0,1,2,3,4,5,6,8,9,10,11]].values
y=data.iloc[:,7].values

In [9]:
x

array([[25.,  1., 49., ...,  0.,  0.,  0.],
       [45., 19., 34., ...,  0.,  0.,  0.],
       [39., 15., 11., ...,  0.,  0.,  0.],
       ...,
       [63., 39., 24., ...,  0.,  0.,  0.],
       [65., 40., 49., ...,  0.,  1.,  0.],
       [28.,  4., 83., ...,  0.,  1.,  1.]])

In [10]:
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [12]:
x_train.shape

(4000, 11)

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [15]:
ann=Sequential()

In [16]:
ann.add(Dense(11,kernel_initializer="random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [17]:
ann.add(Dense(22,kernel_initializer="random_uniform",activation="relu"))

In [18]:
ann.add(Dense(1,kernel_initializer="random_uniform",activation="sigmoid"))

In [19]:
ann.compile("adam","binary_crossentropy",metrics=["accuracy"])

In [21]:
ann.fit(x_train,y_train,batch_size=32,epochs=50)

Epoch 1/50
4000/4000 [==============================] - 0s 61us/sample - loss: 0.0522 - acc: 0.9845
Epoch 2/50
4000/4000 [==============================] - 0s 59us/sample - loss: 0.0521 - acc: 0.9835
Epoch 3/50
4000/4000 [==============================] - 0s 57us/sample - loss: 0.0510 - acc: 0.9845
Epoch 4/50
4000/4000 [==============================] - 0s 55us/sample - loss: 0.0507 - acc: 0.9855
Epoch 5/50
4000/4000 [==============================] - 0s 56us/sample - loss: 0.0499 - acc: 0.9850
Epoch 6/50
4000/4000 [==============================] - 0s 58us/sample - loss: 0.0492 - acc: 0.9862
Epoch 7/50
4000/4000 [==============================] - 0s 59us/sample - loss: 0.0486 - acc: 0.9860
Epoch 8/50
4000/4000 [==============================] - 0s 60us/sample - loss: 0.0483 - acc: 0.9855
Epoch 9/50
4000/4000 [==============================] - 0s 58us/sample - loss: 0.0479 - acc: 0.9860
Epoch 10/50
4000/4000 [==============================] - 0s 55us/sample - loss: 0.0472 - acc: 0.9862

In [22]:
ypred=ann.predict(x_test)

In [23]:
ypred

array([[0.00000000e+00],
       [1.16229057e-06],
       [5.52535057e-05],
       [1.80661678e-04],
       [3.62451673e-02],
       [1.13248825e-06],
       [9.45185661e-01],
       [9.98119235e-01],
       [2.92679667e-02],
       [0.00000000e+00],
       [4.17232513e-07],
       [8.47044587e-03],
       [2.98023224e-08],
       [8.01575184e-03],
       [5.37252724e-02],
       [5.14823198e-03],
       [0.00000000e+00],
       [4.27067280e-05],
       [0.00000000e+00],
       [2.51471996e-04],
       [0.00000000e+00],
       [0.00000000e+00],
       [1.83443129e-02],
       [9.98373151e-01],
       [8.94069672e-08],
       [2.20537186e-06],
       [9.97373998e-01],
       [9.49723125e-01],
       [0.00000000e+00],
       [1.73151493e-05],
       [2.72989273e-05],
       [1.04308128e-06],
       [3.22341919e-04],
       [7.21216202e-06],
       [1.89214945e-04],
       [3.35872173e-05],
       [2.75582075e-04],
       [2.93672085e-04],
       [6.34104013e-04],
       [1.10612214e-02],


In [24]:
y_test

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,

In [28]:
yy=ann.predict(sc.transform([[25,1,49,4,1.6,1,0,1,0,0,0]]))


In [29]:
yy

array([[5.6330588e-08]], dtype=float32)

In [30]:
yp=ann.predict(sc.transform([[25,1,49,4,1.6,1,0,1,0,0,0]]))

In [32]:
yp>0.5

array([[False]])

In [33]:
yp=ann.predict(sc.transform([[54,0,73,7,3.2,0,0,1,1,1,1]]))
yp>0.5

array([[False]])

In [34]:
yp=ann.predict_classes(sc.transform([[34,9,180,1,8.9,3,0,0,0,0,0]]))
yp>0.5

array([[ True]])